/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/model/Exhibition.glb");
  useFrame(({ clock }) => {
    // group.current.geometry.center();
    group.current.rotation.y = Math.sin(clock.getElapsedTime());
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes["UnrecognisableFigure-Artwork"].geometry}
        material={materials.UnrecognisableFigure}
        position={[5.6, 2.05, -10.42]}
        scale={[0.99, 0.74, 0.04]}
      />
      <mesh
        geometry={nodes["Girls_Cutting_Hair-Artwork"].geometry}
        material={materials["Girls Cutting Hair"]}
        position={[-20.68, 2.79, -2.42]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1.48, 1.98, 0.04]}
      />
      <mesh
        geometry={nodes["Heated_2020-Artwork"].geometry}
        material={materials["Heated 2020"]}
        position={[10.65, 2.05, -10.42]}
        scale={[1.73, 1.24, 0.04]}
      />
      <mesh
        geometry={nodes["_Kubika-Opener-Portrait--Artwork"].geometry}
        material={materials["Kubika-Opener-Portrait"]}
        position={[-4.23, 3.21, 10.55]}
        scale={[4.85, 2.25, 0.03]}
      />
      <mesh
        geometry={nodes["Maxim-Artwork"].geometry}
        material={materials.Maxim}
        position={[13.9, 6.03, 6.69]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[1.48, 1.24, 0.04]}
      />
      <mesh
        geometry={nodes["No_Words-Artwork"].geometry}
        material={materials["No Words"]}
        position={[-20.68, 2.05, 2.78]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1.48, 1.24, 0.04]}
      />
      <mesh
        geometry={nodes["People_Puzzle-Artwork"].geometry}
        material={materials["People Puzzle"]}
        position={[6.45, 6.03, -10.42]}
        scale={[1.24, 1.24, 0.04]}
      />
      <mesh
        geometry={nodes["Person_Holding_Plate-Artwork"].geometry}
        material={materials["Person Holding Plate"]}
        position={[11.37, 6.03, -10.42]}
        scale={[1.11, 1.24, 0.04]}
      />
      <mesh
        geometry={nodes["Person_Leaning_Against_a_Chair-Artwork"].geometry}
        material={materials["Person Leaning Against a Chair"]}
        position={[13.9, 6.03, -7.6]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.86, 1.24, 0.04]}
      />
      <mesh
        geometry={nodes["Person_Sitting_On_A_Chair-Artwork"].geometry}
        material={materials["Person Sitting On A Chair-Artwork"]}
        position={[13.9, 2.04, 1.25]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[1.24, 1.24, 0.04]}
      />
      <mesh
        geometry={nodes["Red_Vase_On_A_Table-Artwork"].geometry}
        material={materials["Red Vase On A Table"]}
        position={[-20.68, 2.29, 7.64]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.99, 1.48, 0.04]}
      />
      <mesh
        geometry={nodes["Selfportrait-Artwork"].geometry}
        material={materials.Selfportrait}
        position={[13.9, 2.05, -7.7]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[1.24, 1.24, 0.04]}
      />
      <mesh
        geometry={nodes["Still_Waiting-Artwork"].geometry}
        material={materials["Still Waiting"]}
        position={[13.9, 6.08, 1.25]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.99, 0.74, 0.04]}
      />
      <mesh
        geometry={nodes["Too_Loud-Artwork"].geometry}
        material={materials["Material.002"]}
        position={[13.9, 6.09, -2.81]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.74, 0.99, 0.04]}
      />
      <mesh
        geometry={nodes["Two_Girls_on_Tiles-Artwork"].geometry}
        material={materials["Two Girls on Tiles"]}
        position={[-7.28, 2.05, -10.42]}
        scale={[0.99, 1.24, 0.04]}
      />
      <mesh
        geometry={nodes["Two_Women_on_a_field-Artwork"].geometry}
        material={materials["Two Women on a field-Artwork"]}
        position={[-20.68, 2.3, -7.53]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1.24, 1.48, 0.04]}
      />
      <mesh
        geometry={nodes["What_Is_Real_Anyway-Artwork"].geometry}
        material={materials["What Is Real Anyway"]}
        position={[-3.32, 2.05, -10.42]}
        scale={[0.99, 1.24, 0.04]}
      />
      <mesh
        geometry={nodes["Woman_at_a_pool-Artwork"].geometry}
        material={materials["Woman at a pool"]}
        position={[1, 2.05, -10.42]}
        scale={[0.86, 1.24, 0.04]}
      />
      <mesh
        geometry={nodes["Prototype-Sign"].geometry}
        material={materials.ImageSign}
        position={[-20.71, 1, -0.41]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.19, 0.19, 0.01]}
      />
      <mesh
        geometry={nodes["Two_Girls_on_Tiles-Sign"].geometry}
        material={materials["ImageSign.001"]}
        position={[-5.85, 1.01, -10.44]}
        scale={[0.19, 0.19, 0.01]}
      />
      <mesh
        geometry={nodes["What_Is_Real_Anyway-Sign"].geometry}
        material={materials["ImageSign.002"]}
        position={[-4.7, 1.01, -10.44]}
        scale={[0.19, 0.19, 0.01]}
      />
      <mesh
        geometry={nodes["Prototype-Sign001"].geometry}
        material={materials["ImageSign.003"]}
        position={[-0.29, 1.01, -10.44]}
        scale={[0.19, 0.19, 0.01]}
      />
      <mesh
        geometry={nodes["Prototype-Sign002"].geometry}
        material={materials["ImageSign.004"]}
        position={[7.26, 1.51, -10.44]}
        scale={[0.19, 0.19, 0.01]}
      />
      <mesh
        geometry={nodes["Prototype-Sign003"].geometry}
        material={materials["ImageSign.005"]}
        position={[8.51, 1.01, -10.44]}
        scale={[0.19, 0.19, 0.01]}
      />
      <mesh
        geometry={nodes["Prototype-Sign004"].geometry}
        material={materials["ImageSign.006"]}
        position={[13.93, 1.01, -9.38]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.19, 0.19, 0.01]}
      />
      <mesh
        geometry={nodes["Prototype-Sign005"].geometry}
        material={materials["ImageSign.007"]}
        position={[13.93, 1.01, 2.84]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.19, 0.19, 0.01]}
      />
      <mesh
        geometry={nodes["Prototype-Sign006"].geometry}
        material={materials["ImageSign.008"]}
        position={[13.93, 4.99, -6.32]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.19, 0.19, 0.01]}
      />
      <mesh
        geometry={nodes["Prototype-Sign007"].geometry}
        material={materials["ImageSign.009"]}
        position={[13.93, 5.29, -3.95]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.19, 0.19, 0.01]}
      />
      <mesh
        geometry={nodes["Prototype-Sign008"].geometry}
        material={materials["ImageSign.010"]}
        position={[13.93, 5.53, 2.6]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.19, 0.19, 0.01]}
      />
      <mesh
        geometry={nodes["Prototype-Sign009"].geometry}
        material={materials["ImageSign.011"]}
        position={[13.93, 4.99, 4.81]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.19, 0.19, 0.01]}
      />
      <mesh
        geometry={nodes["Prototype-Sign010"].geometry}
        material={materials["ImageSign.012"]}
        position={[8.12, 4.99, -10.44]}
        scale={[0.19, 0.19, 0.01]}
      />
      <mesh
        geometry={nodes["Prototype-Sign011"].geometry}
        material={materials["ImageSign.013"]}
        position={[9.84, 4.99, -10.44]}
        scale={[0.19, 0.19, 0.01]}
      />
      <mesh
        geometry={nodes["Prototype-Sign012"].geometry}
        material={materials["ImageSign.014"]}
        position={[-20.71, 1, 0.79]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.19, 0.19, 0.01]}
      />
      <mesh
        geometry={nodes["Prototype-Sign013"].geometry}
        material={materials["ImageSign.015"]}
        position={[-20.71, 1, 9.21]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.19, 0.19, 0.01]}
      />
      <mesh
        geometry={nodes["Prototype-Sign014"].geometry}
        material={materials["ImageSign.016"]}
        position={[-20.71, 1, -9.25]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.19, 0.19, 0.01]}
      />
      <mesh
        geometry={nodes.Door.geometry}
        material={nodes.Door.material}
        position={[0, 1.24, 0]}
        scale={0.03}
      />
      <mesh
        geometry={nodes.Pillars.geometry}
        material={nodes.Pillars.material}
        position={[-9.75, 1.62, -8.68]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Floor.geometry}
        material={materials.Floor}
        position={[-0.02, 0, -0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Upstairs.geometry}
        material={materials.Upstairs}
        position={[8.44, 4.31, 9.63]}
      />
      <mesh
        geometry={nodes.Warehouse.geometry}
        material={materials.Warehouse}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Sign_Upstairs.geometry}
        material={nodes.Sign_Upstairs.material}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("/model/Exhibition.glb");
